namespace CheckOut.Models.Dtos;

public class GoogleAuthRequest
{
	/// <summary>
	/// The Google ID token obtained from Google Sign-In SDK on the frontend
	/// </summary>
	public required string IdToken { get; set; }
	
	/// <summary>
	/// Device fingerprint generated by the frontend for device tracking
	/// </summary>
	public required string DeviceFingerprint { get; set; }
}
